### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by ahinchman1** [47deg/scala-days-android#36]
### Value statement:
The Schedule feature is the homepage of the Scala Days application.  Users should be able to use the schedule feature to keep track of talks at a conference event. 

### Gerkins:

- [ ] **When** I open the app, **I should see** a rendered schedule for a single conference event, a hamburger menu for navigation, and an icon to the left.
- [ ] **When** the schedule is rendered, **I should see** that every timeslot will have a room, title of the talk, speaker name, avi, and username (provided in json data)
- [ ] **When** I click on a session or talk, **I should see**:
    - Title of the talk 
    - FAB allowing the user to add to Favorites
    - An calendar icon with the date and time
    - Room
    - Talk description
    - Speakers section with names, avi, and links
- [ ] **When** I am on a session page **and** I click the Speaker's avi, **I should see** that I am taken to their twitter profile page.
- [ ] **When** I click on the hamburger menu, **I should see** the following options:
    - Schedule
    - Social
    - Speakers
    - Tickets
    - Contacts
    - Sponsors
    - Places
    - About
- [ ] **When** I click on the right icon, **I should see** a modal pop up with the following options:
    - All
    - Favorites
- [ ] **When** I click Favorites **and** I have no favorites saved, **I should see** a screen that says there are no favorites and instructions to add favorite sessions.
- [ ] **When** I click Favorites **and** I do have favorites saved, **I should see** the list render only my favorite sessions. These sessions should have a red checkmark to the left.
- [ ] **When** I am on a session page **and** I add a session to my favorites, **I should see**:
    - the FAB icon indicate the session has been added
    - That the session renders a checkmark in the top left of the time slot, either in **All** or **Favorites**

**Comment by ahinchman1** [comment]
Wrong project, moved here - https://github.com/47deg/scala-days-android-kotlin/issues/3
